#!/bin/bash

# Verifica se foi fornecido um argumento
if [ "$#" -eq 0 ]; then
    echo "Erro: Nenhum argumento fornecido."
    exit 1
fi

# Atribui o primeiro argumento a uma variável
input_file="$1"

cat "$input_file" | ./../parser/v8_parser.py -gm2 | ./../escape_rooms/v5python/game.py