#!/bin/bash

# Verifica se foi fornecido um argumento
if [ "$#" -eq 0 ]; then
    echo "Erro: Nenhum argumento fornecido. Pelo menos 1 é necessário para input_file"
    exit 1
fi

# Atribui o primeiro argumento a uma variável
input_file="$1"

# Utiliza shift para remover o primeiro argumento (input_file)
shift

# Constrói a string de argumentos apenas se houver argumentos restantes
args_string=""
if [ "$#" -gt 0 ]; then
    args_string="-args $@"
fi

./../src/parser/parser.py -gm2 -i "$input_file" $args_string | ./../src/engine/game.py